version: 0.2

phases:
  install:
    commands:
      - npm install
      - pip install --upgrade awscli
  pre_build:
    commands:
      - npm test
  build:
    commands:
      - aws cloudformation package --debug --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml
